# Generated by Django 5.1.2 on 2025-12-15 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('contratacion', 'Contratación'), ('asistente_contratacion', 'Asistente Contratación'), ('proveedores', 'Proveedores'), ('paa', 'PAA'), ('docs_contractual', 'Documentos Contractuales'), ('chatbot', 'Chatbot Emil-IA'), ('reportes', 'Reportes')], max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(default='fas fa-folder', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_id', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('password_temporal', models.BooleanField(default=True, verbose_name='Contraseña Temporal')),
                ('fecha_cambio_password', models.DateTimeField(blank=True, null=True)),
                ('es_superusuario_sistema', models.BooleanField(default=False, verbose_name='Super Usuario del Sistema')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, verbose_name='Puede Gestionar Usuarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('modulos_permitidos', models.ManyToManyField(blank=True, related_name='usuarios', to='login.modulo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
