# Generated by Django 5.1.2 on 2025-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre/Razón Social')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='Código')),
                ('es_entidad', models.CharField(default='false', max_length=10, verbose_name='Es Entidad')),
                ('es_grupo', models.CharField(default='false', max_length=10, verbose_name='Es Grupo')),
                ('esta_activa', models.CharField(default='true', max_length=10, verbose_name='Está Activa')),
                ('espyme', models.CharField(default='false', max_length=10, verbose_name='Es PyME')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Creación')),
                ('codigo_categoria_principal', models.CharField(blank=True, max_length=100, verbose_name='Código Categoría Principal')),
                ('descripcion_categoria_principal', models.TextField(blank=True, verbose_name='Descripción Categoría Principal')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('correo', models.CharField(blank=True, max_length=255, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=500, verbose_name='Dirección')),
                ('sitio_web', models.CharField(blank=True, max_length=500, verbose_name='Sitio Web')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('ubicacion', models.TextField(blank=True, verbose_name='Ubicación Completa')),
                ('tipo_empresa', models.CharField(default='PERSONA NATURAL COLOMBIANA', max_length=100, verbose_name='Tipo de Empresa')),
                ('nombre_representante_legal', models.CharField(blank=True, max_length=255, verbose_name='Nombre Representante Legal')),
                ('tipo_doc_representante_legal', models.CharField(blank=True, max_length=50, verbose_name='Tipo Documento Rep. Legal')),
                ('n_mero_doc_representante_legal', models.CharField(blank=True, max_length=50, verbose_name='Número Documento Rep. Legal')),
                ('telefono_representante_legal', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Rep. Legal')),
                ('correo_representante_legal', models.CharField(blank=True, max_length=255, verbose_name='Correo Rep. Legal')),
                ('camaras_comercio', models.TextField(blank=True, verbose_name='Cámaras de Comercio')),
                ('lista_restrictiva', models.CharField(blank=True, max_length=10, verbose_name='Lista Restrictiva')),
                ('inhabilidades', models.TextField(blank=True, verbose_name='Inhabilidades')),
                ('clasificacion_organica', models.CharField(blank=True, max_length=100, verbose_name='Clasificación Orgánica')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.CharField(default='true', max_length=10, verbose_name='Activo en Sistema')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
