# Generated by Django 5.1.2 on 2025-07-30 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la plantilla', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la plantilla')),
                ('archivo_plantilla', models.FileField(help_text='Archivo Word plantilla', upload_to='plantillas/')),
                ('activa', models.BooleanField(default=True, help_text='Si la plantilla está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_referencia', models.CharField(help_text='Referencia del contrato', max_length=100)),
                ('usuario', models.CharField(help_text='Usuario que generó el documento', max_length=150)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo_generado', models.CharField(max_length=255)),
                ('plantilla_usada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_contractual.plantilladocumento')),
            ],
            options={
                'verbose_name': 'Historial de Generación',
                'verbose_name_plural': 'Historial de Generaciones',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
